### ISSUE TITLE
Who is your mysterious third contributor?

### ISSUE THREAD

**Issue by oliverjam** [fac-23/week5-adam-orian#15]
I think you might have an issue with Adam's co-author email: most of your co-authored commits are showing up with a random guy called "mlodz" who has no other commits ever on GitHub 😆 

<img width="328" alt="Screenshot 2022-02-11 at 09 40 41" src="https://user-images.githubusercontent.com/9408641/153569133-8e2dc153-b90b-4f6f-9b4c-4c46832e14c4.png">

**Comment by OrianP** [comment]
That is totally my bad. I accidentally left one digit out of the email 🤦‍♀️ Fixed it with `git rebase -i HEAD~n` and choosing 'reword' on the commits. Thanks for flagging!
